# Generated by Django 4.2.30 on 2026-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_limit_gb',
            field=models.PositiveIntegerField(default=64, help_text="Maximum storage in GB for this user's My Media plus any groups they created."),
        ),
    ]
