# Generated by Django 4.2.30 on 2026-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='can_create_folders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='can_manage_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
    ]
