# Generated by Django 4.2.30 on 2026-09-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_mediafile_captured_at_sharelink_can_create_folders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='can_delete_folders',
            field=models.BooleanField(default=False),
        ),
    ]
